contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Process clusters per species pipeline"
    url: https://github.com/MI-Bioinformatics/poodle
    about: Discussion about the processclusterperspecies pipeline
